springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
jwt.secret=${JWT_SECRET:c2VjcmV0S2V5Rm9yQ2hhbnRpbGx5RGV2RW52aXJvbm1lbnQxMjM0NTY=}
app.seed.default-admin.enabled=true
app.seed.default-admin.password=${APP_DEFAULT_ADMIN_PASSWORD:Admin123*}
